<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentMasterSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // =========================================================================
        // 1. SEED PENELITI (5 Pimpinan Eksekutif + 10 Dewan Peneliti)
        // =========================================================================
        $db->table('peneliti')->truncate();

        $penelitiData = [
            // --- 5 Pimpinan Eksekutif ---
            [
                'category'    => 'pimpinan',
                'name'        => 'Dr. Atika Thahira, S.H., M.H.',
                'role'        => 'Koordinator Pusat Studi / Center Coordinator',
                'role_en'     => 'Center Coordinator',
                'faculty'     => 'Fakultas Hukum (FH) UMRAH',
                'faculty_en'  => 'Faculty of Law UMRAH',
                'focus'       => 'Hukum Maritim dan Hukum Lingkungan',
                'focus_en'    => 'Maritime Law & Environmental Law',
                'cluster'     => 'Hukum Laut Internasional',
                'nip'         => '19820714 200812 2 003',
                'scopus'      => 'Scopus ID: 58164669100',
                'email'       => 'atika.thahira@umrah.ac.id',
                'image'       => 'images/peneliti_atika.jpg',
                'order_num'   => 1,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Dr. Ady Muzwardi, S.IP., M.A., M.H.I.',
                'role'        => 'Head of Research Department',
                'role_en'     => 'Head of Research Department',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Hubungan Internasional, Logistik dan Konektivitas Maritim',
                'focus_en'    => 'International Relations, Maritime Logistics & Connectivity',
                'cluster'     => 'Logistik dan Konektivitas Kepulauan',
                'nip'         => '19810410 200604 1 002',
                'scopus'      => 'Scopus ID: 57727069200',
                'email'       => 'ady.muzwardi@umrah.ac.id',
                'image'       => 'images/peneliti_ady.jpg',
                'order_num'   => 2,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Rachma Indriyani, S.H., LL.M., Ph.D.',
                'role'        => 'Vice of Research Department',
                'role_en'     => 'Vice of Research Department',
                'faculty'     => 'Fakultas Hukum Universitas Sebelas Maret (UNS)',
                'faculty_en'  => 'Faculty of Law Universitas Sebelas Maret',
                'focus'       => 'International Law, Ocean and Law of the Sea, Space Law, Maritime and Fisheries',
                'focus_en'    => 'International Law, Ocean and Law of the Sea, Space Law, Maritime and Fisheries',
                'cluster'     => 'Hukum Laut Internasional',
                'nip'         => '19861118 201212 2 001',
                'scopus'      => 'Scopus ID: 57223868958',
                'email'       => 'rachmaindriyani@staff.uns.ac.id',
                'image'       => 'images/peneliti_rachma.jpg',
                'order_num'   => 3,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Euis Ammelia, S.IP., M.I.P.',
                'role'        => 'Secretary of Research Center',
                'role_en'     => 'Secretary of Research Center',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Politik Internasional dan Pemerintahan Lokal',
                'focus_en'    => 'International Politics & Local Governance',
                'cluster'     => 'Tata Kelola Maritim & Kebijakan Publik',
                'nip'         => '19890512 201803 2 001',
                'scopus'      => 'SINTA ID: 6909581',
                'email'       => 'euis.ammelia@umrah.ac.id',
                'image'       => 'images/peneliti_euis.jpg',
                'order_num'   => 4,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Dedy Afrizal, S.Sos., M.Si., Ph.D.',
                'role'        => 'Head of the Community Service Department',
                'role_en'     => 'Head of the Community Service Department',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Digital Governance, Maritime and Archipelagic',
                'focus_en'    => 'Digital Governance, Maritime and Archipelagic',
                'cluster'     => 'Ketahanan Digital Kepulauan',
                'nip'         => '19780824 200501 1 003',
                'scopus'      => 'Scopus ID: 57222904882',
                'email'       => 'dedy.afrizal@umrah.ac.id',
                'image'       => 'images/peneliti_dedy.jpg',
                'order_num'   => 5,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],

            // --- 10 Dewan Peneliti / Research Fellows ---
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Karla Amelia, S.Pd., M.Sc.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Planktologi, Kualitas Air Laut, Biologi Kelautan & Konservasi Pesisir',
                'focus_en'    => 'Planktology, Marine Water Quality, Marine Biology & Coastal Conservation',
                'cluster'     => 'Ekologi & Sumber Daya Hayati Laut',
                'nip'         => '19910815 201903 2 018',
                'scopus'      => 'SINTA ID: 6712341',
                'email'       => 'karla.amelia@umrah.ac.id',
                'image'       => null,
                'order_num'   => 6,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Dra. Anastasia Wiwik Swastiwi, M.A.',
                'role'        => 'Anggota Dewan Peneliti / Sejarawan Maritim',
                'role_en'     => 'Research Fellow / Maritime Historian',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Sejarah Maritim Melayu, Peradaban Bahari Perbatasan, Budaya & Diplomasi Kawasan ASEAN',
                'focus_en'    => 'Malay Maritime History, Border Oceanic Civilization, Culture & ASEAN Regional Diplomacy',
                'cluster'     => 'Sejarah & Budaya Bahari Perbatasan',
                'nip'         => '19680512 199303 2 001',
                'scopus'      => 'Scopus ID: 57218901234',
                'email'       => 'anastasia.wiwik@umrah.ac.id',
                'image'       => null,
                'order_num'   => 7,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Siti Arieta, S.H., M.A.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Sosiologi Lingkungan Maritim, Hukum Adat Pesisir & Dinamika Sosial Nelayan Perbatasan',
                'focus_en'    => 'Marine Environmental Sociology, Coastal Customary Law & Border Fisheries Social Dynamics',
                'cluster'     => 'Sosiologi Lingkungan & Hukum Adat Pesisir',
                'nip'         => '19750914 200312 2 001',
                'scopus'      => 'SINTA ID: 6019284',
                'email'       => 'siti.arieta@umrah.ac.id',
                'image'       => null,
                'order_num'   => 8,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Sayed Fauzan Riyadi, S.Sos., IMAS',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Geopolitik Maritim Laut Natuna Utara, Keamanan Perbatasan & Tata Kelola Kawasan LCS',
                'focus_en'    => 'North Natuna Sea Maritime Geopolitics, Border Security & SCS Regional Governance',
                'cluster'     => 'Geopolitik & Keamanan Laut Natuna',
                'nip'         => '19800620 200501 1 002',
                'scopus'      => 'Scopus ID: 57209876543',
                'email'       => 'sayedfauzan@umrah.ac.id',
                'image'       => null,
                'order_num'   => 9,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Indah Kartika, S.Kel., M.Si.',
                'role'        => 'Anggota Dewan Peneliti / Koor. SDGs Center UMRAH',
                'role_en'     => 'Research Fellow / Head of UMRAH SDGs Center',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Ekologi Laut Tropis, Blue Carbon, Konservasi Mangrove & Pembangunan Berkelanjutan (SDG 14)',
                'focus_en'    => 'Tropical Marine Ecology, Blue Carbon, Mangrove Conservation & Sustainable Development (SDG 14)',
                'cluster'     => 'SDGs Kemaritiman & Konservasi Tropis',
                'nip'         => '19880402 201504 2 001',
                'scopus'      => 'SINTA ID: 6108472',
                'email'       => 'indah.kartika@umrah.ac.id',
                'image'       => null,
                'order_num'   => 10,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Aditia Ayu Rahma Nabila, S.T., M.T.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Teknik & Teknologi Kemaritiman (FTTK) UMRAH',
                'faculty_en'  => 'Faculty of Engineering & Maritime Technology (FTTK) UMRAH',
                'focus'       => 'Sistem Tenaga Listrik Maritim, Otomasi Instrumentasi Pesisir & Mikrogrid Kepulauan',
                'focus_en'    => 'Marine Electric Power Systems, Coastal Instrumentation Automation & Island Microgrids',
                'cluster'     => 'Instrumentasi & Tenaga Listrik Maritim',
                'nip'         => '19920110 201903 2 015',
                'scopus'      => 'SINTA ID: 6721980',
                'email'       => 'aditia.nabila@umrah.ac.id',
                'image'       => null,
                'order_num'   => 11,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Ahmad Rusdi, M.T.',
                'role'        => 'Koordinator Klaster IV & Anggota Dewan Peneliti',
                'role_en'     => 'Cluster IV Coordinator & Research Fellow',
                'faculty'     => 'Fakultas Teknik & Teknologi Kemaritiman (FTTK) UMRAH',
                'faculty_en'  => 'Faculty of Engineering & Maritime Technology (FTTK) UMRAH',
                'focus'       => 'Energi Terbarukan Kepulauan, Konversi Energi Arus Laut & Mikrogrid Pulau Terpencil',
                'focus_en'    => 'Archipelagic Renewable Energy, Ocean Current Energy Conversion & Remote Island Microgrids',
                'cluster'     => 'Energi Terbarukan di Wilayah Kepulauan',
                'nip'         => '19870315 201404 1 001',
                'scopus'      => 'SINTA ID: 6689021',
                'email'       => 'ahmad.rusdi@umrah.ac.id',
                'image'       => null,
                'order_num'   => 12,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Rinaldo Dwi Putra, S.IP., M.Hub.Int.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Keamanan Maritim Selat Malaka, Kerjasama ASEAN & Diplomasi Perbatasan Kepri',
                'focus_en'    => 'Malacca Strait Maritime Security, ASEAN Border Cooperation & Riau Islands Diplomacy',
                'cluster'     => 'Keamanan & Diplomasi Maritim',
                'nip'         => '19900218 201803 1 001',
                'scopus'      => 'SINTA ID: 6710492',
                'email'       => 'rinaldo.dwiputra@umrah.ac.id',
                'image'       => null,
                'order_num'   => 13,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Ilhamda Fattah Kaloko, S.H., M.H.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Hukum (FH) UMRAH',
                'faculty_en'  => 'Faculty of Law (FH) UMRAH',
                'focus'       => 'Hukum Pidana Laut, Penegakan Hukum ZEE, Illegal Fishing & Peradilan Kemaritiman',
                'focus_en'    => 'Maritime Criminal Law, EEZ Enforcement, IUU Fishing & Oceanic Adjudication',
                'cluster'     => 'Penegakan Hukum Laut & Yurisdiksi Perbatasan',
                'nip'         => '19930722 202012 1 005',
                'scopus'      => 'SINTA ID: 6739812',
                'email'       => 'ilhamda.kaloko@umrah.ac.id',
                'image'       => null,
                'order_num'   => 14,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Benny Manullang, S.Pi., M.Si.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Oseanografi Fisika, Pemodelan Pasut & Arus Selat Riau, Batimetri Dangkal',
                'focus_en'    => 'Physical Oceanography, Riau Strait Tidal & Current Modeling, Shallow Bathymetry',
                'cluster'     => 'Oseanografi Fisika & Akustik Bawah Air',
                'nip'         => '19891104 201602 1 001',
                'scopus'      => 'SINTA ID: 6704512',
                'email'       => 'benny.manullang@umrah.ac.id',
                'image'       => null,
                'order_num'   => 15,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],

            // --- Mitra Riset Eksternal / External Research Fellows ---
            [
                'category'    => 'eksternal',
                'name'        => 'Dr. Joshua Gebert',
                'role'        => 'Peneliti Eksternal / Visiting Scholar',
                'role_en'     => 'External Research Fellow / Visiting Scholar',
                'faculty'     => 'Climate Transformation Programme (CTP) / Nanyang Technological University (NTU)',
                'faculty_en'  => 'Climate Transformation Programme (CTP) / Nanyang Technological University (NTU)',
                'focus'       => 'Urban Planning dan Spatial Analysis Fokus Climate Transformation',
                'focus_en'    => 'Urban Planning & Spatial Analysis focused on Climate Transformation',
                'cluster'     => 'Perencanaan Wilayah & Transformasi Iklim',
                'nip'         => null,
                'scopus'      => 'NTU CTP Fellow',
                'email'       => 'joshua.gebert@ntu.edu.sg',
                'image'       => null,
                'order_num'   => 16,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('peneliti')->insertBatch($penelitiData);

        // =========================================================================
        // 2. SEED PUBLIKASI / POLICY BRIEF
        // =========================================================================
        $db->table('publikasi_brief')->truncate();

        $publikasiData = [
            [
                'number'          => 'PB-05/PSK-UMRAH/2026',
                'type'            => 'policy_brief',
                'title'           => 'Upaya Pengelolaan Kawasan Perbatasan Untuk Mendukung Strategi Diplomasi Menegakkan Kedaulatan Wilayah Di Laut Natuna Utara',
                'title_en'        => 'Border Area Management Efforts to Support Diplomatic Strategy in Enforcing Territorial Sovereignty in the North Natuna Sea',
                'year'            => '2026',
                'author'          => 'Dr. Ady Muzwardi dan Tim Pusat Strategi Kebijakan Isu Khusus Dan Analisis Data BSKLN Kemenlu RI',
                'author_en'       => 'Dr. Ady Muzwardi and Team from Center for Policy Strategy on Special Issues and Data Analysis, Foreign Policy Strategy Agency, Ministry of Foreign Affairs RI',
                'desc'            => 'Implementasi pengelolaan kawasan perbatasan untuk mendukung strategi diplomasi menegakkan kedaulatan wilayah di perbatasan terluar Indonesia di Laut Natuna Utara didukung oleh beberapa kebijakan baik dari Kebijakan Pemerintah Pusat dan Pemerintah Daerah.',
                'desc_en'         => 'Implementation of border area management to support diplomatic strategies for enforcing territorial sovereignty in Indonesia outermost borders in the North Natuna Sea supported by policies from both Central and Regional Governments.',
                'file_path'       => 'uploads/documents/policy_brief_pb05_2026.pdf',
                'downloads_count' => 48,
                'is_published'    => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'number'          => 'PB-06/PSK-UMRAH/2026',
                'type'            => 'policy_brief',
                'title'           => 'Optimalisasi Pengembangan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas',
                'title_en'        => 'Optimization of Free Trade Zone and Free Port Development',
                'year'            => '2026',
                'author'          => 'Dr. Ady Muzwardi dan Pusat Strategi Kebijakan Kawasan Asia Pasifik dan Afrika BSKLN Kemenlu RI',
                'author_en'       => 'Dr. Ady Muzwardi and Center for Policy Strategy for Asia Pacific and Africa Region, Foreign Policy Strategy Agency, Ministry of Foreign Affairs RI',
                'desc'            => 'Kawasan-kawasan strategis untuk menopang pembangunan ekonomi daerah dan nasional. Kawasan Perdagangan Bebas dan Pelabuhan Bebas (KPBPB) adalah salah satu model yang dikembangkan pemerintah dalam mewujudkan Pembangunan di wilayah perbatasan.',
                'desc_en'         => 'Strategic zones to support regional and national economic development. Free Trade Zone and Free Port (KPBPB) is one of the models developed by the government in realizing development in border areas.',
                'file_path'       => 'uploads/documents/policy_brief_pb06_2026.pdf',
                'downloads_count' => 32,
                'is_published'    => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('publikasi_brief')->insertBatch($publikasiData);

        // =========================================================================
        // 3. SEED LAYANAN & JASA KONSULTASI MARITIM
        // =========================================================================
        $db->table('layanan_konsultasi')->truncate();

        $layananData = [
            [
                'slug'         => 'pelabuhan',
                'icon'         => 'fa-anchor',
                'title'        => 'Perancangan & Jasa Kepelabuhanan',
                'title_en'     => 'Port Engineering & Maritime Infrastructure',
                'desc'         => 'Studi Kelayakan (Feasibility Study) Pembangunan Pelabuhan yang komprehensif meliputi 7 pilar: Kajian Kebutuhan & Regulasi, Kajian Hukum & Kelembagaan, Analisis Pasar & Permintaan, Kajian Teknis Dermaga & Hidro-oseanografi, Kelayakan Finansial & Komersial, Analisis Mengenai Dampak Lingkungan (AMDAL), serta Tata Kelola Kerjasama & Mitigasi Risiko.',
                'desc_en'      => 'Port Feasibility Study comprising Need & Compliance Assessments, Legal & Institutional Studies, Market Demand Analysis, Technical Port Studies, Financial & Commercial Feasibility, Environmental & Social Impact, and Partnership & Risk Governance.',
                'code'         => 'SOP-PRT-05',
                'standards'    => 'Pedoman Studi Kelayakan Pelabuhan Kemenhub RI (KP 432/2017 & UU No. 17/2008) & Standar Internasional PIANC',
                'sop_name'     => 'Standar Operasional Prosedur Studi Kelayakan & Perancangan Teknis Fasilitas Pelabuhan',
                'instruments'  => json_encode([
                    'Toolkit Penilaian Kebutuhan, Kepatuhan Regulasi & Kelembagaan Pelabuhan',
                    'Model Prakiraan Permintaan Pasar Angkutan Barang & Penumpang (Origin-Destination)',
                    'Software Simulasi Hidro-Oseanografi & Olah Gerak Kapal (Delft3D / Mike21)',
                    'Matriks Analisis Finansial, Struktur Komersial & Manajemen Risiko Investasi'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Buku Laporan Induk Studi Kelayakan (Feasibility Study - FS) Pelabuhan 7 Pilar Terverifikasi',
                    'Rekomendasi Teknis Rekayasa Sipil Dermaga, Kolam Pelabuhan & Alur Pelayaran',
                    'Lembar Kerja Finansial (IRR, NPV, Payback) & Rencana Mitigasi Risiko Multi-Dimensi'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 1,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'pemberdayaan',
                'icon'         => 'fa-users-gear',
                'title'        => 'Pemberdayaan Masyarakat Perbatasan & Kajian Potensi Maritim',
                'title_en'     => 'Border Community Empowerment & Maritime Potential Studies',
                'desc'         => 'Pendampingan sosial ekonomi nelayan perbatasan, pemetaan komoditas unggulan bahari, penguatan kelembagaan lokal, serta hilirisasi ekonomi pulau-pulau kecil.',
                'desc_en'      => 'Socio-economic assistance for border fishing communities, assessment of prime maritime commodities, local institutional capacity building, and economic downstreaming in small islands.',
                'code'         => 'SOP-COM-06',
                'standards'    => 'Pedoman Pemberdayaan Masyarakat Pesisir KKP & Standar Wilayah Perbatasan Bappenas',
                'sop_name'     => 'SOP Pemetaan Partisipatif Potensi Maritim & Pendampingan Masyarakat Perbatasan',
                'instruments'  => json_encode([
                    'Kit Lapangan Participatory Rural Appraisal (PRA/RRA)',
                    'Geodatabase Spasial Sosial Pesisir & Pulau-Pulau Kecil',
                    'Toolkit Valuasi Ekonomi Sumber Daya Perikanan & Pesisir',
                    'Modul Inkubasi Bisnis Koperasi Nelayan Mandiri'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Laporan Pemetaan Potensi Ekonomi Maritim Perbatasan Terluar',
                    'Dokumen Rencana Aksi (Action Plan) Pemberdayaan Berbasis Komunitas',
                    'Policy Brief Tata Kelola Usaha Nelayan Tradisional di Wilayah Perbatasan'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 2,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'zonasi',
                'icon'         => 'fa-map-location-dot',
                'title'        => 'Pengembangan Tata Ruang Laut & Pulau-Pulau Kecil (RZWP-3-K)',
                'title_en'     => 'Marine Spatial Planning & Small Islands Zoning',
                'desc'         => 'Penyusunan dokumen teknis rencana zonasi wilayah pesisir dan pulau-pulau kecil, kesesuaian ruang laut (PKKPRL), dan mitigasi kebencanaan pesisir.',
                'desc_en'      => 'Technical formulation of coastal zoning plans, small islands spatial allocation, marine spatial suitability assessments, and coastal disaster mitigation.',
                'code'         => 'SOP-MSP-07',
                'standards'    => 'Permen KP No. 28/2021 tentang Penyelenggaraan Penataan Ruang Laut',
                'sop_name'     => 'SOP Penyusunan & Validasi Dokumen Kesesuaian Ruang Laut (PKKPRL)',
                'instruments'  => json_encode([
                    'Perangkat Lunak ArcGIS / QGIS Enterprise & Remote Sensing Imagery',
                    'Platform Pemodelan Kerentanan Pesisir Terhadap Kenaikan Air Laut',
                    'Basis Data Geospasial Alur Pelayaran, Kawasan Konservasi & Budidaya',
                    'Instrumen Penilaian Kesesuaian Ruang Laut (PKKPRL Scoring Framework)'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Album Peta Tematik Rencana Tata Ruang Laut Skala 1:25.000 / 1:50.000',
                    'Naskah Akademis Kesesuaian Pemanfaatan Ruang Laut (PKKPRL)',
                    'Matriks Indikasi Program Zonasi Berkelanjutan & Kajian Lingkungan Hidup Strategis (KLHS)'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 3,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('layanan_konsultasi')->insertBatch($layananData);
    }
}
