<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentMasterSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // =========================================================================
        // 1. SEED PENELITI (5 Pimpinan Eksekutif + 10 Dewan Peneliti)
        // =========================================================================
        $db->table('peneliti')->truncate();
        try {
            $db->query("DELETE FROM sqlite_sequence WHERE name = 'peneliti'");
        } catch (\Throwable $e) {}

        $penelitiData = [
            // --- 5 Pimpinan Eksekutif ---
            [
                'category'    => 'pimpinan',
                'name'        => 'Dr. Atika Thahira, S.H., M.H.',
                'role'        => 'Koordinator Pusat Studi / Center Coordinator',
                'role_en'     => 'Center Coordinator',
                'faculty'     => 'Fakultas Hukum (FH) UMRAH',
                'faculty_en'  => 'Faculty of Law UMRAH',
                'focus'       => 'Hukum Maritim dan Hukum Lingkungan',
                'focus_en'    => 'Maritime Law & Environmental Law',
                'cluster'     => 'Hukum Laut Internasional',
                'nip'         => '19820714 200812 2 003',
                'scopus'      => 'Scopus ID: 58164669100',
                'email'       => 'atika.thahira@umrah.ac.id',
                'image'       => 'images/peneliti_atika.jpg',
                'order_num'   => 1,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Dr. Ady Muzwardi, S.IP., M.A., M.H.I.',
                'role'        => 'Head of Research Department',
                'role_en'     => 'Head of Research Department',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Hubungan Internasional, Logistik dan Konektivitas Maritim',
                'focus_en'    => 'International Relations, Maritime Logistics & Connectivity',
                'cluster'     => 'Logistik dan Konektivitas Kepulauan',
                'nip'         => '19810410 200604 1 002',
                'scopus'      => 'Scopus ID: 57727069200',
                'email'       => 'ady.muzwardi@umrah.ac.id',
                'image'       => 'images/peneliti_ady.jpg',
                'order_num'   => 2,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Rachma Indriyani, S.H., LL.M., Ph.D.',
                'role'        => 'Vice of Research Department',
                'role_en'     => 'Vice of Research Department',
                'faculty'     => 'Fakultas Hukum Universitas Sebelas Maret (UNS)',
                'faculty_en'  => 'Faculty of Law Universitas Sebelas Maret',
                'focus'       => 'International Law, Ocean and Law of the Sea, Space Law, Maritime and Fisheries',
                'focus_en'    => 'International Law, Ocean and Law of the Sea, Space Law, Maritime and Fisheries',
                'cluster'     => 'Hukum Laut Internasional',
                'nip'         => '19861118 201212 2 001',
                'scopus'      => 'Scopus ID: 57223868958',
                'email'       => 'rachmaindriyani@staff.uns.ac.id',
                'image'       => 'images/peneliti_rachma.jpg',
                'order_num'   => 3,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Euis Ammelia, S.IP., M.I.P.',
                'role'        => 'Secretary of Research Center',
                'role_en'     => 'Secretary of Research Center',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Politik Internasional dan Pemerintahan Lokal',
                'focus_en'    => 'International Politics & Local Governance',
                'cluster'     => 'Tata Kelola Maritim & Kebijakan Publik',
                'nip'         => '19890512 201803 2 001',
                'scopus'      => 'SINTA ID: 6909581',
                'email'       => 'euis.ammelia@umrah.ac.id',
                'image'       => 'images/peneliti_euis.jpg',
                'order_num'   => 4,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'pimpinan',
                'name'        => 'Dedy Afrizal, S.Sos., M.Si., Ph.D.',
                'role'        => 'Head of the Community Service Department',
                'role_en'     => 'Head of the Community Service Department',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences UMRAH',
                'focus'       => 'Digital Governance, Maritime and Archipelagic',
                'focus_en'    => 'Digital Governance, Maritime and Archipelagic',
                'cluster'     => 'Ketahanan Digital Kepulauan',
                'nip'         => '19780824 200501 1 003',
                'scopus'      => 'Scopus ID: 57222904882',
                'email'       => 'dedy.afrizal@umrah.ac.id',
                'image'       => 'images/peneliti_dedy.jpg',
                'order_num'   => 5,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],

            // --- 10 Dewan Peneliti / Research Fellows ---
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Karla Amelia, S.Pd., M.Sc.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Planktologi, Kualitas Air Laut, Biologi Kelautan & Konservasi Pesisir',
                'focus_en'    => 'Planktology, Marine Water Quality, Marine Biology & Coastal Conservation',
                'cluster'     => 'Ekologi & Sumber Daya Hayati Laut',
                'nip'         => '19910815 201903 2 018',
                'scopus'      => 'SINTA ID: 6712341',
                'email'       => 'karla.amelia@umrah.ac.id',
                'image'       => null,
                'order_num'   => 6,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Dra. Anastasia Wiwik Swastiwi, M.A.',
                'role'        => 'Anggota Dewan Peneliti / Sejarawan Maritim',
                'role_en'     => 'Research Fellow / Maritime Historian',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Sejarah Maritim Melayu, Peradaban Bahari Perbatasan, Budaya & Diplomasi Kawasan ASEAN',
                'focus_en'    => 'Malay Maritime History, Border Oceanic Civilization, Culture & ASEAN Regional Diplomacy',
                'cluster'     => 'Sejarah & Budaya Bahari Perbatasan',
                'nip'         => '19680512 199303 2 001',
                'scopus'      => 'Scopus ID: 57218901234',
                'email'       => 'anastasia.wiwik@umrah.ac.id',
                'image'       => null,
                'order_num'   => 7,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Siti Arieta, S.H., M.A.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Sosiologi Lingkungan Maritim, Hukum Adat Pesisir & Dinamika Sosial Nelayan Perbatasan',
                'focus_en'    => 'Marine Environmental Sociology, Coastal Customary Law & Border Fisheries Social Dynamics',
                'cluster'     => 'Sosiologi Lingkungan & Hukum Adat Pesisir',
                'nip'         => '19750914 200312 2 001',
                'scopus'      => 'SINTA ID: 6019284',
                'email'       => 'siti.arieta@umrah.ac.id',
                'image'       => null,
                'order_num'   => 8,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Dr. Sayed Fauzan Riyadi, S.Sos., IMAS',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Geopolitik Maritim Laut Natuna Utara, Keamanan Perbatasan & Tata Kelola Kawasan LCS',
                'focus_en'    => 'North Natuna Sea Maritime Geopolitics, Border Security & SCS Regional Governance',
                'cluster'     => 'Geopolitik & Keamanan Laut Natuna',
                'nip'         => '19800620 200501 1 002',
                'scopus'      => 'Scopus ID: 57209876543',
                'email'       => 'sayedfauzan@umrah.ac.id',
                'image'       => null,
                'order_num'   => 9,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Indah Kartika, S.Kel., M.Si.',
                'role'        => 'Anggota Dewan Peneliti / Koor. SDGs Center UMRAH',
                'role_en'     => 'Research Fellow / Head of UMRAH SDGs Center',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Ekologi Laut Tropis, Blue Carbon, Konservasi Mangrove & Pembangunan Berkelanjutan (SDG 14)',
                'focus_en'    => 'Tropical Marine Ecology, Blue Carbon, Mangrove Conservation & Sustainable Development (SDG 14)',
                'cluster'     => 'SDGs Kemaritiman & Konservasi Tropis',
                'nip'         => '19880402 201504 2 001',
                'scopus'      => 'SINTA ID: 6108472',
                'email'       => 'indah.kartika@umrah.ac.id',
                'image'       => null,
                'order_num'   => 10,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Aditia Ayu Rahma Nabila, S.T., M.T.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Teknik & Teknologi Kemaritiman (FTTK) UMRAH',
                'faculty_en'  => 'Faculty of Engineering & Maritime Technology (FTTK) UMRAH',
                'focus'       => 'Sistem Tenaga Listrik Maritim, Otomasi Instrumentasi Pesisir & Mikrogrid Kepulauan',
                'focus_en'    => 'Marine Electric Power Systems, Coastal Instrumentation Automation & Island Microgrids',
                'cluster'     => 'Instrumentasi & Tenaga Listrik Maritim',
                'nip'         => '19920110 201903 2 015',
                'scopus'      => 'SINTA ID: 6721980',
                'email'       => 'aditia.nabila@umrah.ac.id',
                'image'       => null,
                'order_num'   => 11,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Ahmad Rusdi, M.T.',
                'role'        => 'Koordinator Klaster IV & Anggota Dewan Peneliti',
                'role_en'     => 'Cluster IV Coordinator & Research Fellow',
                'faculty'     => 'Fakultas Teknik & Teknologi Kemaritiman (FTTK) UMRAH',
                'faculty_en'  => 'Faculty of Engineering & Maritime Technology (FTTK) UMRAH',
                'focus'       => 'Energi Terbarukan Kepulauan, Konversi Energi Arus Laut & Mikrogrid Pulau Terpencil',
                'focus_en'    => 'Archipelagic Renewable Energy, Ocean Current Energy Conversion & Remote Island Microgrids',
                'cluster'     => 'Energi Terbarukan di Wilayah Kepulauan',
                'nip'         => '19870315 201404 1 001',
                'scopus'      => 'SINTA ID: 6689021',
                'email'       => 'ahmad.rusdi@umrah.ac.id',
                'image'       => null,
                'order_num'   => 12,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Rinaldo Dwi Putra, S.IP., M.Hub.Int.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Sosial & Ilmu Politik (FISIP) UMRAH',
                'faculty_en'  => 'Faculty of Social & Political Sciences (FISIP) UMRAH',
                'focus'       => 'Keamanan Maritim Selat Malaka, Kerjasama ASEAN & Diplomasi Perbatasan Kepri',
                'focus_en'    => 'Malacca Strait Maritime Security, ASEAN Border Cooperation & Riau Islands Diplomacy',
                'cluster'     => 'Keamanan & Diplomasi Maritim',
                'nip'         => '19900218 201803 1 001',
                'scopus'      => 'SINTA ID: 6710492',
                'email'       => 'rinaldo.dwiputra@umrah.ac.id',
                'image'       => null,
                'order_num'   => 13,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Ilhamda Fattah Kaloko, S.H., M.H.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Hukum (FH) UMRAH',
                'faculty_en'  => 'Faculty of Law (FH) UMRAH',
                'focus'       => 'Hukum Pidana Laut, Penegakan Hukum ZEE, Illegal Fishing & Peradilan Kemaritiman',
                'focus_en'    => 'Maritime Criminal Law, EEZ Enforcement, IUU Fishing & Oceanic Adjudication',
                'cluster'     => 'Penegakan Hukum Laut & Yurisdiksi Perbatasan',
                'nip'         => '19930722 202012 1 005',
                'scopus'      => 'SINTA ID: 6739812',
                'email'       => 'ilhamda.kaloko@umrah.ac.id',
                'image'       => null,
                'order_num'   => 14,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'dewan_peneliti',
                'name'        => 'Benny Manullang, S.Pi., M.Si.',
                'role'        => 'Anggota Dewan Peneliti',
                'role_en'     => 'Research Fellow',
                'faculty'     => 'Fakultas Ilmu Kelautan & Perikanan (FIKP) UMRAH',
                'faculty_en'  => 'Faculty of Marine Sciences & Fisheries (FIKP) UMRAH',
                'focus'       => 'Oseanografi Fisika, Pemodelan Pasut & Arus Selat Riau, Batimetri Dangkal',
                'focus_en'    => 'Physical Oceanography, Riau Strait Tidal & Current Modeling, Shallow Bathymetry',
                'cluster'     => 'Oseanografi Fisika & Akustik Bawah Air',
                'nip'         => '19891104 201602 1 001',
                'scopus'      => 'SINTA ID: 6704512',
                'email'       => 'benny.manullang@umrah.ac.id',
                'image'       => null,
                'order_num'   => 15,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],

            // --- Mitra Riset Eksternal / External Research Fellows ---
            [
                'category'    => 'eksternal',
                'name'        => 'Dr. Joshua Gebert',
                'role'        => 'Peneliti Eksternal / Visiting Scholar',
                'role_en'     => 'External Research Fellow / Visiting Scholar',
                'faculty'     => 'Climate Transformation Programme (CTP) / Nanyang Technological University (NTU)',
                'faculty_en'  => 'Climate Transformation Programme (CTP) / Nanyang Technological University (NTU)',
                'focus'       => 'Urban Planning dan Spatial Analysis Fokus Climate Transformation',
                'focus_en'    => 'Urban Planning & Spatial Analysis focused on Climate Transformation',
                'cluster'     => 'Perencanaan Wilayah & Transformasi Iklim',
                'nip'         => null,
                'scopus'      => 'NTU CTP Fellow',
                'email'       => 'joshua.gebert@ntu.edu.sg',
                'image'       => null,
                'order_num'   => 16,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category'    => 'eksternal',
                'name'        => 'Prof. Dr. Sidik Jatmika, M.Si.',
                'role'        => 'Peneliti Senior Eksternal / Guru Besar HI UMY',
                'role_en'     => 'Senior External Fellow / Professor of International Relations',
                'faculty'     => 'Departemen Hubungan Internasional, Universitas Muhammadiyah Yogyakarta (UMY)',
                'faculty_en'  => 'Department of International Relations, Universitas Muhammadiyah Yogyakarta (UMY)',
                'focus'       => 'Human Security, Islam dan Politik Global, Futures Studies',
                'focus_en'    => 'Human Security, Islam and Global Politics, Futures Studies',
                'cluster'     => 'Diplomasi Maritim & Hubungan Internasional',
                'nip'         => null,
                'scopus'      => 'UMY Professor',
                'email'       => 'sidikjatmika@umy.ac.id',
                'image'       => null,
                'order_num'   => 17,
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('peneliti')->insertBatch($penelitiData);

        // =========================================================================
        // 2. SEED PUBLIKASI / POLICY BRIEF
        // =========================================================================
        $db->table('publikasi_brief')->truncate();
        try {
            $db->query("DELETE FROM sqlite_sequence WHERE name = 'publikasi_brief'");
        } catch (\Throwable $e) {}

        $publikasiData = [
            [
                'number'          => 'PB-05/PSK-UMRAH/2026',
                'type'            => 'policy_brief',
                'title'           => 'Upaya Pengelolaan Kawasan Perbatasan Untuk Mendukung Strategi Diplomasi Menegakkan Kedaulatan Wilayah Di Laut Natuna Utara',
                'title_en'        => 'Border Area Management Efforts to Support Diplomatic Strategy in Enforcing Territorial Sovereignty in the North Natuna Sea',
                'year'            => '2026',
                'author'          => 'Dr. Ady Muzwardi dan Tim Pusat Strategi Kebijakan Isu Khusus Dan Analisis Data BSKLN Kemenlu RI',
                'author_en'       => 'Dr. Ady Muzwardi and Team from Center for Policy Strategy on Special Issues and Data Analysis, Foreign Policy Strategy Agency, Ministry of Foreign Affairs RI',
                'desc'            => 'Implementasi pengelolaan kawasan perbatasan untuk mendukung strategi diplomasi menegakkan kedaulatan wilayah di perbatasan terluar Indonesia di Laut Natuna Utara didukung oleh beberapa kebijakan baik dari Kebijakan Pemerintah Pusat dan Pemerintah Daerah.',
                'desc_en'         => 'Implementation of border area management to support diplomatic strategies for enforcing territorial sovereignty in Indonesia outermost borders in the North Natuna Sea supported by policies from both Central and Regional Governments.',
                'file_path'       => 'uploads/documents/policy_brief_pb05_2026.pdf',
                'downloads_count' => 48,
                'is_published'    => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'number'          => 'PB-06/PSK-UMRAH/2026',
                'type'            => 'policy_brief',
                'title'           => 'Optimalisasi Pengembangan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas',
                'title_en'        => 'Optimization of Free Trade Zone and Free Port Development',
                'year'            => '2026',
                'author'          => 'Dr. Ady Muzwardi dan Pusat Strategi Kebijakan Kawasan Asia Pasifik dan Afrika BSKLN Kemenlu RI',
                'author_en'       => 'Dr. Ady Muzwardi and Center for Policy Strategy for Asia Pacific and Africa Region, Foreign Policy Strategy Agency, Ministry of Foreign Affairs RI',
                'desc'            => 'Kawasan-kawasan strategis untuk menopang pembangunan ekonomi daerah dan nasional. Kawasan Perdagangan Bebas dan Pelabuhan Bebas (KPBPB) adalah salah satu model yang dikembangkan pemerintah dalam mewujudkan Pembangunan di wilayah perbatasan.',
                'desc_en'         => 'Strategic zones to support regional and national economic development. Free Trade Zone and Free Port (KPBPB) is one of the models developed by the government in realizing development in border areas.',
                'file_path'       => 'uploads/documents/policy_brief_pb06_2026.pdf',
                'downloads_count' => 32,
                'is_published'    => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('publikasi_brief')->insertBatch($publikasiData);

        // =========================================================================
        // 3. SEED LAYANAN & JASA KONSULTASI MARITIM
        // =========================================================================
        $db->table('layanan_konsultasi')->truncate();
        try {
            $db->query("DELETE FROM sqlite_sequence WHERE name = 'layanan_konsultasi'");
        } catch (\Throwable $e) {}

        $layananData = [
            [
                'slug'         => 'batimetri',
                'icon'         => 'fa-water',
                'title'        => 'Jasa Survei Batimetri & Hidro-Oseanografi Kelautan',
                'title_en'     => 'Marine Bathymetric & Hydro-Oceanographic Survey',
                'desc'         => 'Pemetaan batimetri resolusi tinggi untuk alur pelayaran kapal, perencanaan dermaga pelabuhan, pemodelan hidrodinamika arus pasang surut, studi erosi pantai, dan analisis sedimentasi muara perairan Kepulauan Riau & Natuna.',
                'desc_en'      => 'High-resolution bathymetric mapping for navigation channels, port pier planning, tidal current hydrodynamic modeling, coastal erosion studies, and sedimentation analytics in Riau Islands and Natuna waters.',
                'code'         => 'SOP-HYD-01',
                'standards'    => 'Standar Hidrografi Internasional IHO S-44 (Special Order & Order 1a), Pedoman Survei Hidros Pushidrosal TNI AL, dan Standar BIG.',
                'sop_name'     => 'SOP Survei Batimetri Akustik & Pengukuran Hidro-Oseanografi Lapangan',
                'instruments'  => json_encode([
                    'Singlebeam & Multibeam Echo Sounder (MBES) Dual Frequency',
                    'Acoustic Doppler Current Profiler (ADCP) 600/300 kHz',
                    'Automatic Tide Gauge (AWLR) & Stasiun Pasut Real-time',
                    'Dual-Frequency RTK-DGPS Marine Navigation & GNSS Positioning',
                    'Sound Velocity Profiler (SVP) Sonar Calibration Probe'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Peta Batimetri Digital Berstandar IHO / Pushidrosal (Skala 1:1.000 - 1:10.000)',
                    'Model Hidrodinamika 2D/3D Kecepatan & Arah Arus Pasang Surut',
                    'Laporan Analisis Oseanografi Fisika, Kedalaman Alur & Rekomendasi Navigasi Kapal'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 1,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'kualitas-air',
                'icon'         => 'fa-flask-vial',
                'title'        => 'Analisis Kualitas Air Laut & Laboratorium Lingkungan Maritim',
                'title_en'     => 'Seawater Quality Analysis & Marine Environmental Laboratory',
                'desc'         => 'Uji laboratorium baku mutu perairan laut, pengukuran parameter oseanografi kimia, fisika, dan biologi guna keperluan rona lingkungan awal AMDAL/UKL-UPL, izin pembuangan air lindi/efluen, dan kajian daya dukung perairan budidaya.',
                'desc_en'      => 'Accredited laboratory testing of seawater environmental standards, physico-chemical-biological oceanographic parameters for baseline EIA/AMDAL studies, effluent discharge permits, and aquaculture carrying capacity.',
                'code'         => 'SOP-ENV-02',
                'standards'    => 'PP RI No. 22/2021 Lampiran VIII (Baku Mutu Air Laut Pelabuhan, Biota Laut & Wisata Bahari) serta Standar Uji Laboratorium SNI / ISO 17025.',
                'sop_name'     => 'SOP Pengambilan Sampel & Pengujian Baku Mutu Parameter Lingkungan Air Laut',
                'instruments'  => json_encode([
                    'CTD (Conductivity, Temperature, Depth) Multiparameter Oceanographic Probe',
                    'Spectrophotometer UV-Vis Kelautan & Analisis Nutrien (Nitrat, Fosfat, Amonia)',
                    'Water Sampler Niskin & Van Dorn Horisontal/Vertikal 5 Liter',
                    'Portable Turbidimeter, DO Meter, Salinometer & pH-Meter Multi-Sensor',
                    'Van Veen Sediment Grab Sampler & Ayakan Granulometri Sedimen Dasar'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Sertifikat Hasil Uji Laboratorium Terverifikasi Parameter Fisika-Kimia Laut',
                    'Laporan Evaluasi Indeks Pencemaran & Baku Mutu Air Laut (PP 22/2021)',
                    'Dokumen Kajian Daya Dukung Lingkungan Perairan untuk Kelayakan AMDAL / UKL-UPL'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 2,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'pelabuhan',
                'icon'         => 'fa-anchor',
                'title'        => 'Perancangan & Jasa Studi Kelayakan (FS) Kepelabuhanan',
                'title_en'     => 'Port Engineering & Maritime Infrastructure Feasibility Study',
                'desc'         => 'Penyusunan Studi Kelayakan (Feasibility Study) Fasilitas Pelabuhan komprehensif 7 pilar: Kebutuhan & Regulasi, Hukum & Kelembagaan, Analisis Pasar & Hinterland, Teknis Dermaga & Hidro-oseanografi, Finansial & Komersial, AMDAL Lingkungan, serta Mitigasi Risiko Investasi.',
                'desc_en'      => 'Comprehensive 7-Pillar Port Feasibility Study comprising Need & Compliance, Legal & Institutional Studies, Market Demand & Hinterland, Technical Berth & Hydrodynamics, Financial & Commercial Feasibility, Environmental Impact, and Investment Risk Mitigation.',
                'code'         => 'SOP-PRT-03',
                'standards'    => 'Pedoman Studi Kelayakan Pelabuhan Kemenhub RI (KP 432/2017 & UU No. 17/2008), RIPN, serta Standar Internasional PIANC.',
                'sop_name'     => 'SOP Penyusunan Feasibility Study (FS) & Perancangan Teknis Fasilitas Pelabuhan',
                'instruments'  => json_encode([
                    'Toolkit Penilaian Kebutuhan, Kepatuhan Regulasi & Kelembagaan Pelabuhan',
                    'Model Prakiraan Permintaan Pasar Angkutan Barang & Penumpang (Origin-Destination)',
                    'Software Simulasi Hidro-Oseanografi Kolam Labuh & Olah Gerak Kapal (Delft3D / Mike21)',
                    'Matriks Kelayakan Finansial, Struktur Komersial (KPBU/B2B) & Analisis Sensitivitas'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Buku Laporan Induk Feasibility Study (FS) 7 Pilar Pelabuhan Terverifikasi Tim Ahli',
                    'Rekomendasi Teknis Desain Dermaga, Kedalaman Kolam Putar & Alur Pelayaran',
                    'Lembar Kerja Finansial (IRR, NPV, Payback Period) & Strategi Mitigasi Risiko Investasi'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 3,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'zonasi',
                'icon'         => 'fa-map-location-dot',
                'title'        => 'Pengembangan Tata Ruang Laut & Pulau-Pulau Kecil (RZWP-3-K)',
                'title_en'     => 'Marine Spatial Planning & Small Islands Zoning (RZWP-3-K)',
                'desc'         => 'Konsultasi teknis dan pendampingan penyusunan rencana zonasi wilayah pesisir dan pulau-pulau kecil (RZWP-3-K), dokumen Kesesuaian Pemanfaatan Ruang Laut (PKKPRL), penetapan kawasan konservasi perairan daerah, dan mitigasi konflik spasial kelautan.',
                'desc_en'      => 'Technical consultancy for coastal and small islands spatial planning (RZWP-3-K), Marine Space Suitability (PKKPRL) dossiers, marine protected area delineation, and spatial conflict resolution models.',
                'code'         => 'SOP-MSP-04',
                'standards'    => 'Permen Kelautan dan Perikanan No. 28/2021 tentang Penyelenggaraan Penataan Ruang Laut, UU Cipta Kerja, dan Standar Geospasial BIG.',
                'sop_name'     => 'SOP Penyusunan & Validasi Dokumen Kesesuaian Ruang Laut (PKKPRL)',
                'instruments'  => json_encode([
                    'Perangkat Lunak ArcGIS / QGIS Enterprise & Spatial Database PostgreSQL/PostGIS',
                    'Citra Satelit Multitemporal Resolusi Tinggi (Sentinel-2, PlanetScope, Landsat-9)',
                    'Drone Pemetaan Pesisir (VTOL RGB 42 MP & Multispektral) Garis Pantai',
                    'Platform Analisis Kesesuaian & Matriks Tumpang Tindih Pemanfaatan Ruang Laut'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Album Peta Tematik Rencana Tata Ruang Laut Skala 1:25.000 / 1:50.000 Berstandar BIG',
                    'Naskah Akademis Kesesuaian Pemanfaatan Ruang Laut (PKKPRL)',
                    'Matriks Indikasi Program Zonasi Berkelanjutan & Kajian Lingkungan Hidup Strategis (KLHS)'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 4,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'pemberdayaan',
                'icon'         => 'fa-users-gear',
                'title'        => 'Pemberdayaan Masyarakat Pesisir Perbatasan & Valuasi Bahari',
                'title_en'     => 'Coastal Community Empowerment & Maritime Resource Valuation',
                'desc'         => 'Pendampingan sosial-ekonomi nelayan perbatasan terluar Natuna-Anambas, pemetaan rantai pasok komoditas perikanan unggulan, valuasi ekonomi sumber daya hayati laut, serta inkubasi kelembagaan koperasi nelayan pesisir.',
                'desc_en'      => 'Socio-economic mentoring for border fishing communities in Natuna-Anambas, marine commodity supply chain mapping, economic valuation of living marine resources, and coastal cooperative institutional incubation.',
                'code'         => 'SOP-COM-05',
                'standards'    => 'Pedoman Pemberdayaan Masyarakat Pesisir KKP RI, Standar Perencanaan Wilayah Perbatasan Bappenas & Kemendes PDTT.',
                'sop_name'     => 'SOP Kajian Potensi Wilayah Maritim & Pendampingan Nelayan Perbatasan',
                'instruments'  => json_encode([
                    'Kit Lapangan Participatory Rural Appraisal (PRA/RRA) & Rapid Social Assessment',
                    'Geodatabase Sosial-Spasial Sebaran Fishing Ground & Wilayah Tangkap Adat Nelayan',
                    'Toolkit Valuasi Ekonomi Sumber Daya Hayati (Travel Cost Method, CVM & Market Price Proxy)',
                    'Modul Standardisasi Tata Kelola Koperasi Nelayan & Hilirisasi Produk Perikanan'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Laporan Pemetaan Potensi Ekonomi Maritim Wilayah Perbatasan Terluar',
                    'Dokumen Rencana Aksi (Action Plan) Pemberdayaan Komunitas Nelayan Berkelanjutan',
                    'Policy Brief Rekomendasi Kebijakan Kesejahteraan Nelayan untuk Pemerintah Pusat & Daerah'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 5,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'slug'         => 'pelatihan-gis',
                'icon'         => 'fa-chalkboard-user',
                'title'        => 'Pelatihan Teknis & Sertifikasi Geospasial Kemaritiman',
                'title_en'     => 'Maritime Geospatial Training & Professional Certification',
                'desc'         => 'Program pelatihan intensif dan sertifikasi kompetensi GIS kelautan, penginderaan jauh satelit oseanografi, serta pemetaan hidrografi bagi instansi pemerintah (Dinas Kelautan/Bappeda), konsultan, industri maritim, dan akademisi.',
                'desc_en'      => 'Intensive training and competency certification in marine GIS, oceanographic satellite remote sensing, and hydrographic mapping for government agencies, environmental consultants, maritime industries, and researchers.',
                'code'         => 'SOP-TRN-06',
                'standards'    => 'Standar Kompetensi Kerja Nasional Indonesia (SKKNI) Bidang Informasi Geospasial & Standar Akreditasi LPPM UMRAH.',
                'sop_name'     => 'SOP Penyelenggaraan Pelatihan Teknis & Uji Kompetensi Geospasial Kelautan',
                'instruments'  => json_encode([
                    'Fasilitas Laboratorium Komputasi GIS & Pemodelan Numerik Kampus Dompak UMRAH',
                    'Modul Praktikum Berbasis Software Industri (ArcGIS Pro, QGIS, SNAP Sentinel Toolboxes)',
                    'Kumpulan Dataset Spasial Riil Kepulauan Riau, Selat Malaka, dan Laut Natuna Utara',
                    'Instruktur Ahli Geospasial Laut Bersertifikat IHO Cat-A & Asosiasi Surveyor Kelautan'
                ], JSON_UNESCAPED_UNICODE),
                'deliverables' => json_encode([
                    'Sertifikat Pelatihan Resmi LPPM UMRAH dengan Jam Pelajaran Terakreditasi',
                    'Portofolio Hasil Proyek Analisis Spasial & Pemodelan Laut Setiap Peserta',
                    'Akses Repositori Modul Pelatihan Digital, Script Geoprocessing & Konsultasi Lanjutan'
                ], JSON_UNESCAPED_UNICODE),
                'order_num'    => 6,
                'is_active'    => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ]
        ];

        $db->table('layanan_konsultasi')->insertBatch($layananData);
    }
}
