<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UnduhanSeeder extends Seeder
{
    public function run()
    {
        $documents = [
            // 1. SOP Laboratorium (4 docs)
            [
                'code'        => 'SOP-PSK-01',
                'slug'        => 'sop-oseanografi',
                'title'       => 'SOP Pelaksanaan Survei Batimetri dan Pemetaan Akustik Bawah Laut',
                'category'    => 'SOP Laboratorium',
                'category_id' => 'sop',
                'file_type'   => 'PDF',
                'file_size'   => '2.4 MB',
                'year'        => '2026',
                'downloads'   => 342,
                'desc'        => 'Prosedur standar kalibrasi multibeam sonar, instalasi sensor pasang surut, sound velocity profile (SVP), dan pemrosesan data kedalaman sesuai standar IHO S-44.',
                'created_at'  => '2026-01-15 08:00:00',
                'updated_at'  => '2026-01-15 08:00:00',
            ],
            [
                'code'        => 'SOP-PSK-02',
                'slug'        => 'sop-mutu-air',
                'title'       => 'SOP Pengambilan Sampel dan Uji Mutu Air Laut Terakreditasi',
                'category'    => 'SOP Laboratorium',
                'category_id' => 'sop',
                'file_type'   => 'PDF',
                'file_size'   => '1.8 MB',
                'year'        => '2025',
                'downloads'   => 289,
                'desc'        => 'Standar operasional baku mutu air laut untuk perikanan budidaya, wisata bahari, dan pemantauan perairan industri pelabuhan sesuai regulasi PP No. 22 Tahun 2021.',
                'created_at'  => '2025-11-20 08:00:00',
                'updated_at'  => '2025-11-20 08:00:00',
            ],
            [
                'code'        => 'SOP-PSK-03',
                'slug'        => 'sop-blue-carbon',
                'title'       => 'SOP Inventarisasi dan Penghitungan Cadangan Karbon Biru Mangrove',
                'category'    => 'SOP Laboratorium',
                'category_id' => 'sop',
                'file_type'   => 'PDF',
                'file_size'   => '2.1 MB',
                'year'        => '2025',
                'downloads'   => 415,
                'desc'        => 'Metodologi terstandarisasi sampling biomassa pohon atas dan bawah, nekromassa, serta penghitungan cadangan karbon sedimen tanah mangrove pulau-pulau Kepri.',
                'created_at'  => '2025-10-10 08:00:00',
                'updated_at'  => '2025-10-10 08:00:00',
            ],
            [
                'code'        => 'SOP-PSK-04',
                'slug'        => 'sop-drone-pantai',
                'title'       => 'SOP Pengoperasian Drone Nirawak untuk Pemetaan Garis Pantai',
                'category'    => 'SOP Laboratorium',
                'category_id' => 'sop',
                'file_type'   => 'PDF',
                'file_size'   => '1.5 MB',
                'year'        => '2026',
                'downloads'   => 198,
                'desc'        => 'Panduan keselamatan penerbangan pesisir, penentuan Ground Control Points (GCP) geodetik, dan pengolahan ortofoto resolusi tinggi untuk monitoring abrasi.',
                'created_at'  => '2026-02-01 08:00:00',
                'updated_at'  => '2026-02-01 08:00:00',
            ],

            // 2. Policy Brief & Publikasi (5 docs)
            [
                'code'        => 'PB-PSK-05',
                'slug'        => 'pb-diplomasi-perbatasan-natuna',
                'title'       => 'Policy Brief: Upaya Pengelolaan Kawasan Perbatasan Untuk Mendukung Strategi Diplomasi Menegakkan Kedaulatan Wilayah Di Laut Natuna Utara',
                'category'    => 'Policy Brief & Publikasi',
                'category_id' => 'policy-brief',
                'file_type'   => 'PDF',
                'file_size'   => '3.8 MB',
                'year'        => '2026',
                'downloads'   => 412,
                'desc'        => 'Implementasi pengelolaan kawasan perbatasan untuk mendukung strategi diplomasi menegakkan kedaulatan wilayah di perbatasan terluar Indonesia di Laut Natuna Utara didukung oleh beberapa kebijakan baik dari Kebijakan Pemerintah Pusat dan Pemerintah Daerah. Penyusun: Dr. Ady Muzwardi dan Tim BSKLN.',
                'created_at'  => '2026-03-01 08:00:00',
                'updated_at'  => '2026-03-01 08:00:00',
            ],
            [
                'code'        => 'PB-PSK-04',
                'slug'        => 'pb-kedaulatan-natuna-lcs',
                'title'       => 'Policy Brief: Penguatan Kedaulatan & Tata Kelola ZEE Laut Natuna Utara Terhadap Dinamika Laut Cina Selatan',
                'category'    => 'Policy Brief & Publikasi',
                'category_id' => 'policy-brief',
                'file_type'   => 'PDF',
                'file_size'   => '4.1 MB',
                'year'        => '2026',
                'downloads'   => 684,
                'desc'        => 'Rekomendasi strategis pengawasan ruang laut terpadu berbasis sensor satelit, penegakan batas landas kontinen sesuai UNCLOS 1982, serta pengawalan armada nelayan tangkap nasional di ZEE Laut Natuna Utara.',
                'created_at'  => '2026-02-25 08:00:00',
                'updated_at'  => '2026-02-25 08:00:00',
            ],
            [
                'code'        => 'PB-PSK-01',
                'slug'        => 'pb-logistik-pesisir',
                'title'       => 'Policy Brief: Strategi Penguatan Konektivitas Logistik Pesisir & Disparitas Harga di Kepri',
                'category'    => 'Policy Brief & Publikasi',
                'category_id' => 'policy-brief',
                'file_type'   => 'PDF',
                'file_size'   => '3.2 MB',
                'year'        => '2026',
                'downloads'   => 520,
                'desc'        => 'Kajian empiris trayek kapal perintis dan optimasi jaringan logistik kebutuhan pokok gugusan pulau terluar Natuna-Anambas guna menekan inflasi komoditas pangan.',
                'created_at'  => '2026-01-20 08:00:00',
                'updated_at'  => '2026-01-20 08:00:00',
            ],
            [
                'code'        => 'PB-PSK-02',
                'slug'        => 'pb-tata-ruang-laut',
                'title'       => 'Policy Brief: Harmonisasi Tata Ruang Laut: Mitigasi Konflik Tambang Pasir & Nelayan',
                'category'    => 'Policy Brief & Publikasi',
                'category_id' => 'policy-brief',
                'file_type'   => 'PDF',
                'file_size'   => '2.9 MB',
                'year'        => '2025',
                'downloads'   => 476,
                'desc'        => 'Tinjauan yuridis UNCLOS 1982 dan zonasi tangkap nelayan tradisional terhadap dampak ekologis konsesi pertambangan pasir laut dan alur pelayaran tanker internasional.',
                'created_at'  => '2025-12-05 08:00:00',
                'updated_at'  => '2025-12-05 08:00:00',
            ],
            [
                'code'        => 'PB-PSK-03',
                'slug'        => 'pb-karbon-biru',
                'title'       => 'Policy Brief: Valuasi Ekonomi Karbon Biru dan Skema Insentif Konservasi Masyarakat',
                'category'    => 'Policy Brief & Publikasi',
                'category_id' => 'policy-brief',
                'file_type'   => 'PDF',
                'file_size'   => '3.5 MB',
                'year'        => '2025',
                'downloads'   => 388,
                'desc'        => 'Rekomendasi skema pendanaan pasar karbon biru berbasis kearifan Melayu pesisir sebagai sumber pendapatan baru masyarakat pengelola ekosistem mangrove Bintan.',
                'created_at'  => '2025-11-15 08:00:00',
                'updated_at'  => '2025-11-15 08:00:00',
            ],

            // 3. Template & Kerjasama (3 docs)
            [
                'code'        => 'FORM-PSK-01',
                'slug'        => 'form-pengajuan-riset',
                'title'       => 'Formulir Pengajuan Inisiasi Kerjasama Riset dan Studi Kelautan',
                'category'    => 'Template & Kerjasama',
                'category_id' => 'template',
                'file_type'   => 'DOCX',
                'file_size'   => '420 KB',
                'year'        => '2026',
                'downloads'   => 612,
                'desc'        => 'Format baku permohonan kerjasama penelitian, kajian kelayakan maritim, dan survei lapangan dari kementerian, pemerintah daerah, BUMN, dan sektor swasta.',
                'created_at'  => '2026-01-05 08:00:00',
                'updated_at'  => '2026-01-05 08:00:00',
            ],
            [
                'code'        => 'FORM-PSK-02',
                'slug'        => 'form-mou-pks',
                'title'       => 'Template Nota Kesepahaman (MoU) & Perjanjian Kerjasama (PKS) Kemaritiman',
                'category'    => 'Template & Kerjasama',
                'category_id' => 'template',
                'file_type'   => 'DOCX',
                'file_size'   => '510 KB',
                'year'        => '2026',
                'downloads'   => 443,
                'desc'        => 'Draft klausul hukum standar kerjasama kelembagaan, kepemilikan Hak Kekayaan Intelektual (HKI), publikasi bersama, dan pembagian hak data riset kelautan.',
                'created_at'  => '2026-01-05 08:00:00',
                'updated_at'  => '2026-01-05 08:00:00',
            ],
            [
                'code'        => 'FORM-PSK-03',
                'slug'        => 'form-sewa-lab',
                'title'       => 'Formulir Permohonan Penggunaan Laboratorium Komputasi GIS & Wahana Riset',
                'category'    => 'Template & Kerjasama',
                'category_id' => 'template',
                'file_type'   => 'DOCX',
                'file_size'   => '380 KB',
                'year'        => '2026',
                'downloads'   => 275,
                'desc'        => 'Formulir reservasi perangkat komputasi geospasial, workstation analisis citra satelit, drone survei pantai, dan kapal riset mini Seabird Kampus Dompak.',
                'created_at'  => '2026-01-05 08:00:00',
                'updated_at'  => '2026-01-05 08:00:00',
            ],

            // 4. Panduan & Regulasi (2 docs)
            [
                'code'        => 'GUIDE-PSK-01',
                'slug'        => 'panduan-hibah-malaka',
                'title'       => 'Panduan Program Hibah Riset Kolaboratif Kemaritiman Selat Malaka 2026',
                'category'    => 'Panduan & Regulasi',
                'category_id' => 'panduan',
                'file_type'   => 'PDF',
                'file_size'   => '2.7 MB',
                'year'        => '2026',
                'downloads'   => 780,
                'desc'        => 'Buku panduan lengkap ketentuan pengajuan proposal hibah riset, rincian anggaran biaya (RAB), jadwal seleksi, dan luaran wajib jurnal internasional bereputasi.',
                'created_at'  => '2026-01-02 08:00:00',
                'updated_at'  => '2026-01-02 08:00:00',
            ],
            [
                'code'        => 'REG-PSK-01',
                'slug'        => 'regulasi-etik-kemaritiman',
                'title'       => 'Kode Etik Riset Lapangan Kelautan & Keselamatan Operasional Perairan',
                'category'    => 'Panduan & Regulasi',
                'category_id' => 'panduan',
                'file_type'   => 'PDF',
                'file_size'   => '1.9 MB',
                'year'        => '2025',
                'downloads'   => 310,
                'desc'        => 'Regulasi keselamatan kerja maritim (K3), standar operasional perlindungan periset di laut, perizinan survei perairan perbatasan, dan etika penanganan sampel biota.',
                'created_at'  => '2025-09-15 08:00:00',
                'updated_at'  => '2025-09-15 08:00:00',
            ],
        ];

        $builder = $this->db->table('unduhan');
        $builder->truncate();
        $builder->insertBatch($documents);
    }
}

